name: coody_delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.15.3
  firebase_auth: ^4.17.3
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  image_picker: ^1.0.6
  rename_app: ^1.3.2
  timeago: ^3.6.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/playstore.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
